const $=s=>document.querySelector(s);let stream,step=0,photos=[],currentCoin=null;const panels=[...document.querySelectorAll('.panel')];function show(id){panels.forEach(p=>p.classList.toggle('active',p.id===id));scrollTo(0,0)}
const labels={'0.01':'1 centavo','0.05':'5 centavos','0.10':'10 centavos','0.25':'25 centavos','0.50':'50 centavos','1':'R$ 1'};
const catalog={'0.01':['1994','1995','1996','1997','1998','1999','2000','2001','2002','2003','2004'],'0.05':['1994','1995','1996','1997','1998','1999','2000','2001','2002','2003','2004','2005','2006','2007','2008','2009','2010','2011','2012','2013','2014','2015','2016','2017','2018','2019','2019A','2020','2021','2022','2023','2024','2025'],'0.10':['1994','1995','1996','1997','1998','1999','2000','2001','2002','2003','2004','2005','2006','2007','2008','2009','2010','2011','2012','2013','2014','2015','2016','2017','2018','2019','2020','2021','2022','2023','2024','2025'],'0.25':['1994','1995','1996','1997','1998','1999','2000','2001','2002','2003','2004','2005','2006','2007','2008','2009','2010','2011','2012','2013','2014','2015','2016','2017','2018','2019','2020','2021','2022','2023','2024','2025'],'0.50':['1994','1995','1996','1997','1998','2000','2001','2002','2003','2005','2006','2007','2008','2009','2010','2011','2012','2013','2014','2015','2016','2017','2018','2019','2019A','2020','2021','2022','2023','2024','2025'],'1':['1994','1998','1999','2002','2003','2004','2005','2006','2007','2008','2009','2010','2011','2012','2013','2014','2015','2016','2017','2018','2019','2020','2021','2022','2023','2024','2025']};
const variants=[
{v:'0.05',y:'2019A',n:'Marca A',type:'oficial',how:'Letra A pequena junto à era. Identifica produção da Royal Dutch Mint.'},
{v:'0.10',y:'1995',n:'FAO 50 anos',type:'oficial',how:'Mãos oferecendo broto + FAO 1945/1995. Tiragem oficial: 1 milhão.'},
{v:'0.25',y:'1995',n:'FAO 50 anos',type:'oficial',how:'Cena de cultivo + FAO 1945/1995. Tiragem oficial: 1 milhão.'},
{v:'0.25',y:'1995',n:'Mula / reverso incompatível',type:'catalogado',how:'Procure combinação de cunhos/desenho incompatível; se o valor/desenho não corresponder ao padrão, retenha.'},
{v:'0.50',y:'2012',n:'Mula 2012',type:'catalogado',how:'Anverso/reverso incompatível com o padrão de 50 centavos/Rio Branco. Erro de produção documentado em referência numismática.'},
{v:'0.50',y:'2018',n:'Diferenças de cunho/fonte',type:'catalogado',how:'Compare principalmente RIO BRANCO, letras e desenho com exemplar normal do mesmo ano.'},
{v:'0.50',y:'2019',n:'Com e sem marca de casa cunhadora',type:'oficial',how:'Sem A = Casa da Moeda do Brasil; com A = Royal Dutch Mint. Guarde 2019A separadamente.'},
{v:'0.50',y:'2019A',n:'Marca A',type:'oficial',how:'A pequena próxima à era. Produção estrangeira oficialmente identificada pelo BCB.'},
{v:'0.50',y:'2020',n:'Legenda/borda diferente',type:'catalogado',how:'Compare tamanho e forma das letras de ORDEM E PROGRESSO / BRASIL com outro exemplar.'},
{v:'1',y:'1998',n:'Direitos Humanos',type:'oficial',how:'Desenho comemorativo dos 50 anos da Declaração Universal. Apenas 600 mil peças.'},
{v:'1',y:'1998',n:'Reverso invertido/horizontal',type:'catalogado',how:'Segure o anverso em pé e gire a moeda no eixo vertical; reverso fora da orientação padrão deve ser retido.'},
{v:'1',y:'1999',n:'Baixa tiragem regular',type:'oficial',how:'Moeda comum, mas emissão oficial de apenas 3,84 milhões. Guarde exemplares bons.'},
{v:'1',y:'2005',n:'40 anos Banco Central',type:'oficial',how:'Motivo comemorativo do BCB. Tiragem 40 milhões.'},
{v:'1',y:'2012',n:'Entrega da Bandeira Olímpica',type:'oficial',how:'Desenho ligado à passagem Londres–Rio; versão de circulação deve ser separada das comuns.'},
{v:'1',y:'2014',n:'Rio 2016 — modalidades',type:'oficial',how:'Há desenhos olímpicos específicos; cada desenho é um tipo de coleção.'},
{v:'1',y:'2015',n:'Rio 2016 / 50 anos BCB',type:'oficial',how:'Existem múltiplos desenhos de circulação no ano. Colecione cada desenho separadamente.'},
{v:'1',y:'2016',n:'Rio 2016 — modalidades e mascotes',type:'oficial',how:'Vários desenhos olímpicos/paralímpicos. Cada desenho conta como entrada distinta.'},
{v:'1',y:'2019',n:'25 anos do Real — beija-flor',type:'oficial',how:'Beija-flor alimentando filhotes. Tiragem autorizada: 25 milhões.'},
{v:'1',y:'2024',n:'30 anos do Real',type:'oficial',how:'Versão comemorativa oficial; guardar separada da moeda regular.'},
{v:'1',y:'2025',n:'60 anos Banco Central',type:'oficial',how:'Versão comemorativa oficial; guardar separada da regular.'}
];
const genericErrors=['Reverso invertido (aprox. 180°)','Reverso horizontal/rotacionado','Cunho descentralizado','Batida dupla / duplicação','Cunho quebrado / excesso de metal de cunho','Disco cortado/incompleto','Disco ou material incompatível','Núcleo deslocado em R$1','Núcleo ausente/anormal em R$1','Mula: anverso e reverso incompatíveis','Borda/serrilha/legenda fora do padrão','Data, letra ou elemento duplicado/anormal'];
const alerts={'0.10':{'1995':'red','1999':'yellow'},'0.25':{'1995':'red'},'0.50':{'1998':'yellow','2000':'yellow','2001':'yellow','2012':'yellow','2019A':'yellow','2020':'yellow'},'1':{'1998':'yellow','1999':'yellow','2005':'yellow','2012':'yellow','2014':'yellow','2015':'yellow','2016':'yellow','2019':'yellow','2024':'yellow','2025':'yellow'}};
const collection=()=>{try{return JSON.parse(localStorage.getItem('coinCollection')||'{}')}catch{return{}}};function coinKey(v,y,c=false){return`${v}|${y}|${c?'especial':'normal'}`}function saveCollection(c){localStorage.setItem('coinCollection',JSON.stringify(c));updateSummary()}function updateSummary(){const c=collection(),types=Object.keys(c).length,total=Object.values(c).reduce((a,x)=>a+(x.qty||0),0);$('#collectionSummary').innerHTML=`🗂️ Coleção: <b>${types} tipos</b> • <b>${total} moedas</b>`}
function renderCollection(){const c=collection(),filter=$('#collectionFilter').value;let html='',have=0,possible=0;Object.entries(catalog).forEach(([v,years])=>{if(filter!=='all'&&filter!==v)return;html+=`<h3>${labels[v]}</h3><div class="facts">`;years.forEach(y=>{possible++;const n=c[coinKey(v,y,false)],s=c[coinKey(v,y,true)];if(n||s)have++;html+=`<div>${n||s?'✅':'⬜'} <b>${y}</b>${n?` • normal ×${n.qty}`:''}${s?` • ⭐ especial ×${s.qty}`:''}</div>`});html+='</div>'});$('#collectionStats').innerHTML=`Progresso: <b>${have}/${possible}</b> anos/tipos básicos`;$('#collectionList').innerHTML=html}
function renderVariants(){const f=$('#variantFilter').value,rows=variants.filter(x=>f==='all'||x.v===f);let html=rows.map(x=>`<div class="facts"><b>${labels[x.v]} • ${x.y} — ${x.n}</b><br><small>${x.type==='oficial'?'🏛️ emissão/característica oficial':'🔬 referência numismática'}</small><br>${x.how}</div>`).join('');html+=`<h3>⚠️ Erros gerais — qualquer ano</h3><div class="facts">${genericErrors.map(x=>`<div>□ ${x}</div>`).join('')}</div>`;$('#variantList').innerHTML=html}
async function tuneCamera(track){try{const caps=track.getCapabilities?.()||{},a=[];if((caps.focusMode||[]).includes('continuous'))a.push({focusMode:'continuous'});if(caps.zoom)a.push({zoom:Math.min(caps.zoom.max,Math.max(caps.zoom.min,1.5))});if(a.length)await track.applyConstraints({advanced:a})}catch{}}async function start(){try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:3840},height:{ideal:2160}},audio:false});$('#video').srcObject=stream;await tuneCamera(stream.getVideoTracks()[0]);step=0;photos=[];$('#side').textContent='FRENTE • 10–15 cm';$('#capture').textContent='● Fotografar frente';show('camera')}catch{alert('Não consegui abrir a câmera traseira.')}}function stop(){stream?.getTracks().forEach(t=>t.stop())}function snap(){const v=$('#video'),c=$('#canvas');c.width=v.videoWidth;c.height=v.videoHeight;c.getContext('2d').drawImage(v,0,0);photos.push(c.toDataURL('image/jpeg',.98));if(step++===0){$('#side').textContent='VERSO • 10–15 cm';$('#capture').textContent='● Fotografar verso'}else{stop();autoIdentify()}}
async function readPhoto(src,n){$('#scanStatus').textContent=`Lendo ${n}...`;try{return((await Tesseract.recognize(src,'eng')).data.text||'').toUpperCase()}catch{return''}}function detectValue(t){if(/\b50\b/.test(t))return'0.50';if(/\b25\b/.test(t))return'0.25';if(/\b10\b/.test(t))return'0.10';if(/\b5\b\s*CENT/.test(t))return'0.05';if(/\b1\b\s*CENT/.test(t))return'0.01';if(/1\s*REAL/.test(t))return'1';return''}async function autoIdentify(){show('scanning');$('#scanFront').src=$('#front').src=photos[0];$('#scanBack').src=$('#back').src=photos[1];const text=((await readPhoto(photos[0],'frente'))+' '+(await readPhoto(photos[1],'verso'))).replace(/\s+/g,' '),ys=[...text.matchAll(/(?:19|20)\d{2}/g)].map(x=>x[0]).filter(y=>+y>=1994&&+y<=2026);let year=ys[0]||'',value=detectValue(text);if(year==='2019'&&/(2019\s*A|A\s*2019)/.test(text)&&(value==='0.50'||value==='0.05'))year='2019A';const comm=/FAO|DIREITOS|HUMAN|OLIMP|PARALIMP|BANCO\s*CENTRAL|BEIJA/.test(text);if(value)$('#value').value=value;if(year)$('#year').value=year;$('#commemorative').checked=comm;$('#anomaly').checked=false;$('#detected').textContent=`Automático: ${value?labels[value]:'valor NÃO reconhecido'} • ${year||'ano NÃO reconhecido'}`;show('identify');if(value&&year)analyze()}
function result(level,title,text,facts){$('#status').className='status '+level;$('#status').textContent=level==='red'?'🔴 ALERTA FORTE — SEPARE':level==='yellow'?'🟡 SEPARE PARA CONFERIR':'🟢 SEM ALERTA PELO ANO';$('#resultTitle').textContent=title;$('#resultText').textContent=text;$('#facts').innerHTML=facts;show('result')}function owned(){if(!currentCoin)return;const e=collection()[coinKey(currentCoin.v,currentCoin.y,currentCoin.comm)];$('#ownedState').innerHTML=e?`✅ Já possui • quantidade ${e.qty}`:'⭐ Nova para sua coleção básica.'}
function analyze(){const val=$('#value').value,year=$('#year').value.trim().toUpperCase().replace(/[^0-9A]/g,''),comm=$('#commemorative').checked,anom=$('#anomaly').checked;if(!/^(19|20)\d{2}A?$/.test(year)){currentCoin=null;return result('yellow','NÃO DESCARTE','Ano não reconhecido. Separe.','Falha de leitura = retenção.')}const y=year.slice(0,4),matches=variants.filter(x=>x.v===val&&(x.y===year||x.y===y));currentCoin={v:val,y:year,comm,anom};let level=(alerts[val]||{})[year]||(alerts[val]||{})[y]||'green';if(matches.length&&level==='green')level='yellow';if(comm&&level==='green')level='yellow';if(anom)level='red';result(level,`${labels[val]} • ${year}`,anom?'Anomalia marcada: não gaste nem limpe.':'Confira os itens específicos abaixo antes de liberar.',`Checklist geral: <b>giro • duplicação • descentralização • borda • disco/núcleo • desenho incompatível</b>.`);$('#variantMatches').innerHTML=matches.length?`<b>🔬 Checklist deste ano:</b><br>${matches.map(x=>`• <b>${x.n}</b>: ${x.how}`).join('<br>')}`:'<b>Sem variante específica cadastrada para este ano.</b> Ainda faça o checklist geral.';owned()}
$('#saveCoin').onclick=()=>{if(!currentCoin)return;const c=collection(),k=coinKey(currentCoin.v,currentCoin.y,currentCoin.comm);c[k]=c[k]||{qty:0};c[k].qty++;saveCollection(c);owned()};$('#collectionBtn').onclick=()=>{renderCollection();show('collection')};$('#collectionFilter').onchange=renderCollection;$('#collectionHome').onclick=()=>show('home');$('#variantsBtn').onclick=()=>{renderVariants();show('variants')};$('#variantFilter').onchange=renderVariants;$('#variantsHome').onclick=()=>show('home');$('#start').onclick=start;$('#capture').onclick=snap;$('#cancel').onclick=()=>{stop();show('home')};$('#manual').onclick=()=>show('identify');$('#analyze').onclick=analyze;$('#again').onclick=start;$('#edit').onclick=()=>show('identify');$('#backHome').onclick=()=>show('home');updateSummary();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');