// Hands-free capture layer. Keeps manual capture as fallback.
let autoStableFrames=0,autoCooldown=false,autoCountdownTimer=null,autoLastScore=0;
const AUTO_FOCUS_SCORE=1800;
const AUTO_STABLE_FRAMES=3;
const AUTO_DELTA=420;

function resetAutoCapture(){autoStableFrames=0;autoLastScore=0;autoCooldown=false;clearInterval(autoCountdownTimer);autoCountdownTimer=null;const c=document.querySelector('#countdown');if(c)c.textContent='';document.querySelector('.camera')?.classList.remove('ready','captured')}

async function automaticSnap(){if(autoCooldown||!stream)return;autoCooldown=true;document.querySelector('.camera')?.classList.add('ready');let n=2;const cd=document.querySelector('#countdown');if(cd)cd.textContent=n;autoCountdownTimer=setInterval(()=>{n--;if(n>0){if(cd)cd.textContent=n;return}clearInterval(autoCountdownTimer);autoCountdownTimer=null;if(cd)cd.textContent='';const now=sharpness();if(now<AUTO_FOCUS_SCORE*.72){autoCooldown=false;autoStableFrames=0;document.querySelector('.camera')?.classList.remove('ready');return}document.querySelector('.camera')?.classList.add('captured');photos.push(cropCoinData());if(step++===0){document.querySelector('#side').textContent='VERSO';document.querySelector('#captureProgress').textContent='2/2';document.querySelector('#focusHint').textContent='Vire a moeda e centralize';document.querySelector('#capture').textContent='Fotografar verso manualmente';setTimeout(()=>{autoCooldown=false;autoStableFrames=0;autoLastScore=0;document.querySelector('.camera')?.classList.remove('ready','captured')},1200)}else{stop();document.querySelector('#captureProgress').textContent='2/2';autoIdentify()}},650)}

startFocusMeter=function(){if(focusTimer)clearInterval(focusTimer);resetAutoCapture();focusTimer=setInterval(()=>{lastSharpness=sharpness();const el=document.querySelector('#focusState');const hint=document.querySelector('#focusHint');const delta=Math.abs(lastSharpness-autoLastScore);autoLastScore=lastSharpness;if(lastSharpness>=AUTO_FOCUS_SCORE){el.className='focusState good';el.textContent=`🟢 NÍTIDO • ${Math.round(lastSharpness)}`;hint.textContent=autoCooldown?'Mantenha parado…':'Mantenha parado';document.querySelector('.camera')?.classList.add('ready');if(delta<AUTO_DELTA)autoStableFrames++;else autoStableFrames=Math.max(0,autoStableFrames-1);if(autoStableFrames>=AUTO_STABLE_FRAMES&&!autoCooldown)automaticSnap()}else if(lastSharpness>500){el.className='focusState waiting';el.textContent=`🟡 QUASE • ${Math.round(lastSharpness)} / ${AUTO_FOCUS_SCORE}`;hint.textContent='Ajustando foco…';autoStableFrames=0;document.querySelector('.camera')?.classList.remove('ready')}else{el.className='focusState bad';el.textContent=`🔴 SEM NITIDEZ • ${Math.round(lastSharpness)}`;hint.textContent='Afaste/aproxime ou troque a lente';autoStableFrames=0;document.querySelector('.camera')?.classList.remove('ready')}},350)};

const originalStart=start;start=async function(){resetAutoCapture();document.querySelector('#captureProgress').textContent='1/2';document.querySelector('#captureMode').textContent='CAPTURA AUTOMÁTICA';await originalStart();document.querySelector('#capture').textContent='Fotografar frente manualmente'};

document.querySelector('#capture').onclick=()=>{if(autoCooldown)return;photos.push(cropCoinData());autoCooldown=true;if(step++===0){document.querySelector('#side').textContent='VERSO';document.querySelector('#captureProgress').textContent='2/2';document.querySelector('#focusHint').textContent='Vire a moeda e centralize';document.querySelector('#capture').textContent='Fotografar verso manualmente';setTimeout(()=>{autoCooldown=false;autoStableFrames=0},900)}else{stop();autoIdentify()}};
